[features]
seeds = false
skip-lint = false

[programs.localnet]
matrix_system = "BWnK662qst6w8D8hDpetToB8CUYoUTpS9hWJoF1KupTk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
